### ISSUE TITLE
Complete hashing of netcdf files

### ISSUE THREAD

**Issue by nichannah** [aidanheerdegen/nchash#2]
Hi Aidan, 

There are lots of things that nccopy does which change the header while the data should remain the same. For example it puts the per-variable deflate and shuffle level in. Do you have any thoughts on a option to compare contents only? Do you know of any other tools that do this already? 

Thanks, 

Nic

**Comment by aidanheerdegen** [comment]
You can store md5 hashes as an attribute for each variable

This guy was interested in the same thing, documented some of it and ended up with `nco` as the best way to implement it. 

https://github.com/willirath/netcdf-hash

I believe nco is also what is used for CMIP data

**Comment by nichannah** [comment]
Thank you. nccmp also looks quite promising. https://gitlab.com/remikz/nccmp

**Comment by aidanheerdegen** [comment]
I no longer use `nchash` for quick hashing as it only works with netCDF files. Now I do a something similar, but just hash the first nMB (where n = 50 or so) and the date and modification time. I figure I'm a good chance of noticing if anything changes and reading that much of the start of a file is likely to include the header, or some of it. I'm really just after detecting if there is any change and then making sure with a full hash.
